# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/UCT Work/EEE/High Perfomance Embedded/FPGA/Prac4/Prac4Clock.srcs/sources_1/ip/seconds_counter/seconds_counter.xci
# IP: The module: 'seconds_counter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/UCT Work/EEE/High Perfomance Embedded/FPGA/Prac4/Prac4Clock.srcs/sources_1/ip/seconds_counter/seconds_counter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'seconds_counter'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/UCT Work/EEE/High Perfomance Embedded/FPGA/Prac4/Prac4Clock.srcs/sources_1/ip/seconds_counter/seconds_counter.xci
# IP: The module: 'seconds_counter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/UCT Work/EEE/High Perfomance Embedded/FPGA/Prac4/Prac4Clock.srcs/sources_1/ip/seconds_counter/seconds_counter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'seconds_counter'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
